"""
ZapalloAI — Actualiza los notebooks para que sean thin wrappers de scripts.

Transforma:
  01_exploracion_datos.ipynb  → EDA que importa config.py
  02_preprocesamiento.ipynb   → 02_evaluacion.ipynb (evalúa best.pt)
  03_entrenamiento_yolov11.ipynb → 03_despliegue.ipynb (TFLite inference)
"""

import json
from pathlib import Path

NOTEBOOKS_DIR = Path(__file__).resolve().parents[1] / "notebooks"
CONFIG_IMPORT = 'import sys; sys.path.insert(0, str(Path.cwd() / "model"))'

KERNEL_SPEC = {
    "display_name": "Python 3",
    "language": "python",
    "name": "python3",
}

LANG_INFO = {
    "name": "python",
    "version": "3.12.0",
}


def _cells(cell_list):
    return cell_list


def code(source_lines, cell_id=None):
    return {
        "cell_type": "code",
        "execution_count": None,
        "id": cell_id or "",
        "metadata": {},
        "outputs": [],
        "source": source_lines if isinstance(source_lines, list) else [source_lines],
    }


def md(source_lines):
    return {
        "cell_type": "markdown",
        "id": "",
        "metadata": {},
        "source": source_lines if isinstance(source_lines, list) else [source_lines],
    }


def notebook(cells):
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": dict(KERNEL_SPEC),
            "language_info": dict(LANG_INFO),
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


# ─── Notebook 01: EDA ───────────────────────────────────────────────

NOTEBOOK_01_CELLS = _cells([

    md([
        "# ZapalloAI — Notebook 01: Exploración de Datos (EDA)\n",
        "\n",
        "**Universidad de las Fuerzas Armadas ESPE**  \n",
        "**Estudiantes:** César Loor, Camilo Orrico  \n",
        "**Docente:** Ing. Doris Chicaiza\n",
        "\n",
        "Análisis exploratorio del dataset procesado. Este notebook **importa `config.py`**",
        "y lee el dataset ya preprocesado por `model/scripts/preprocess.py`.\n",
        "\n",
        "---\n",
        "\n",
        "## Clases del modelo\n",
        "\n",
        "YOLO asigna los índices de clase en **orden alfabético** de los nombres de carpeta:\n",
        "\n",
        "| Índice | Clase | Descripción |\n",
        "|---|---|---|\n",
        "| 0 | `downy_mildew` | Mildiú velloso |\n",
        "| 1 | `healthy` | Hoja sana |\n",
        "| 2 | `leaf_curl` | Enrollamiento foliar |\n",
        "| 3 | `mosaic_virus` | Virus del mosaico |\n",
        "| 4 | `red_beetle` | Daño por escarabajo rojo |\n",
    ]),

    code([
        "# ── 0. Dependencias ─────────────────────────────────────────\n",
        "try:\n",
        "    import matplotlib, PIL, pandas, seaborn, imagehash, cv2, numpy\n",
        "    print('OK - Dependencias ya instaladas')\n",
        "except ImportError:\n",
        "    import subprocess, sys\n",
        "    subprocess.run([sys.executable, '-m', 'pip', 'install', '-q',\n",
        "                    'matplotlib', 'Pillow', 'pandas', 'seaborn',\n",
        "                    'imagehash', 'opencv-python-headless'], check=False)\n",
        "    print('OK - Dependencias instaladas')\n",
    ], cell_id="deps"),

    code([
        "# ── 1. Importar config.py y parámetros EDA ─────────────────\n",
        "import sys\n",
        "from pathlib import Path\n",
        "\n",
        "sys.path.insert(0, str(Path.cwd() / 'model'))\n",
        "from config import CLASSES, PROCESSED_DIR, RAW_DIR, RANDOM_SEED\n",
        "\n",
        "import random\n",
        "import numpy as np\n",
        "import multiprocessing as mp\n",
        "\n",
        "random.seed(RANDOM_SEED)\n",
        "np.random.seed(RANDOM_SEED)\n",
        "\n",
        "EDA_SAMPLE_RES   = 200  # imágenes para análisis de resoluciones\n",
        "EDA_SAMPLE_QUAL  = 100  # imágenes para análisis de calidad\n",
        "EDA_N_VISUAL     = 4    # muestras visuales por clase\n",
        "N_WORKERS  = min(8, mp.cpu_count())\n",
        "\n",
        "print(f'Dataset raw      : {RAW_DIR}')\n",
        "print(f'Dataset procesado: {PROCESSED_DIR}')\n",
        "print(f'Clases ({len(CLASSES)}): {CLASSES}')\n",
        "print(f'CPU workers      : {N_WORKERS}')\n",
        "print()\n",
        "\n",
        "proc_ok = PROCESSED_DIR.exists() and any(PROCESSED_DIR.iterdir())\n",
        "raw_ok  = RAW_DIR.exists()\n",
        "print(f'Dataset raw    : {\"OK\" if raw_ok else \"NO ENCONTRADO\"}')\n",
        "msg = \"OK\" if proc_ok else \"NO ENCONTRADO\"\n",
        "if not proc_ok:\n",
        "    msg += \" — ejecuta: python model/scripts/preprocess.py\"\n",
        "print(f'Dataset proc   : {msg}')\n",
    ], cell_id="config"),

    code([
        "# ── 1b. Cargar resumen rapido desde dataset_summary.json ──\n",
        "summary_path = PROCESSED_DIR.parent / 'dataset_summary.json'\n",
        "if summary_path.exists():\n",
        "    import json\n",
        "    data = json.loads(summary_path.read_text(encoding='utf-8'))\n",
        "    print('=== Resumen RAPIDO (desde dataset_summary.json) ===')\n",
        "    print(f'Total: {data[\"total_images\"]:,} imagenes')\n",
        "    print(f'  Train: {data[\"total\"][\"train\"]:,}  Val: {data[\"total\"][\"val\"]:,}'\n",
        "          f'  Test: {data[\"total\"][\"test\"]:,}')\n",
        "    print(f'Balance: {data[\"balance_ratio\"]}x  Clases: {len(data[\"classes\"])}')\n",
        "    print('(Celdas siguientes dan analisis detallado)')\n",
        "else:\n",
        "    print('dataset_summary.json no encontrado.')\n",
        "    print('Ejecuta primero: python model/scripts/preprocess.py')\n",
        "    print('Celdas siguientes contaran manualmente.)')\n",
    ], cell_id="summary_json"),

    code([
        "# ── 2. Conteo paralelo de imágenes por split y clase ───────\n",
        "import pandas as pd\n",
        "from concurrent.futures import ThreadPoolExecutor\n",
        "import time\n",
        "\n",
        "def _count_one(args):\n",
        "    d, cls, split = args\n",
        "    if not d.exists():\n",
        "        return {'split': split, 'clase': cls, 'count': 0}\n",
        "    n = 0\n",
        "    for ext in ('*.jpg', '*.jpeg', '*.png'):\n",
        "        n += sum(1 for _ in d.glob(ext))\n",
        "    return {'split': split, 'clase': cls, 'count': n}\n",
        "\n",
        "def count_images_parallel(base):\n",
        "    tasks = [(base / split / cls, cls, split)\n",
        "             for split in ['train', 'val', 'test']\n",
        "             for cls in CLASSES]\n",
        "    t0 = time.perf_counter()\n",
        "    with ThreadPoolExecutor(max_workers=N_WORKERS) as ex:\n",
        "        rows = list(ex.map(_count_one, tasks))\n",
        "    print(f'  Tiempo: {time.perf_counter()-t0:.2f}s ({N_WORKERS} workers)')\n",
        "    return pd.DataFrame(rows)\n",
        "\n",
        "df = count_images_parallel(PROCESSED_DIR)\n",
        "pivot = df.pivot(index='clase', columns='split', values='count')\n",
"pivot = pivot[['train', 'val', 'test']]\n",
        "pivot['TOTAL'] = pivot.sum(axis=1)\n",
        "pivot.loc['TOTAL'] = pivot.sum()\n",
        "print('\\n=== Distribucion del Dataset Procesado ===')\n",
        "print(pivot.to_string())\n",
    ], cell_id="counting"),

    code([
        "# ── 3. Grafico de barras apiladas ───────────────────────────\n",
        "import matplotlib.pyplot as plt\n",
        "import matplotlib\n",
        "matplotlib.rcParams.update({'font.family': 'DejaVu Sans', 'font.size': 11})\n",
        "\n",
        "df_plot = pivot.drop('TOTAL').drop(columns='TOTAL').reset_index()\n",
        "COLORS = {'train': '#2D6A4F', 'val': '#52B788', 'test': '#95D5B2'}\n",
        "\n",
        "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
        "\n",
        "# Barras apiladas\n",
        "ax = axes[0]\n",
        "bottom = [0] * len(CLASSES)\n",
        "for split in ['train', 'val', 'test']:\n",
        "    vals = [df_plot.loc[df_plot.clase == c, split].values[0] for c in CLASSES]\n",
        "    ax.bar(CLASSES, vals, bottom=bottom, label=split, color=COLORS[split])\n",
        "    bottom = [b + v for b, v in zip(bottom, vals)]\n",
        "ax.set_title('Distribucion por clase y split')\n",
        "ax.set_ylabel('Imagenes')\n",
        "ax.set_xticks(range(len(CLASSES)))\n",
        "ax.set_xticklabels(CLASSES, rotation=20, ha='right')\n",
        "ax.legend()\n",
        "\n",
        "# Solo train — balance de clases\n",
        "ax2 = axes[1]\n",
        "train_counts = [df_plot.loc[df_plot.clase == c, 'train'].values[0] for c in CLASSES]\n",
        "bars = ax2.barh(CLASSES, train_counts, color='#2D6A4F')\n",
        "for bar, val in zip(bars, train_counts):\n",
        "    ax2.text(val + 30, bar.get_y() + bar.get_height() / 2, f'{val:,}', va='center')\n",
        "ax2.set_title('Imagenes en TRAIN por clase')\n",
        "ax2.set_xlabel('Imagenes')\n",
        "ax2.invert_yaxis()\n",
        "\n",
        "plt.suptitle('ZapalloAI — EDA del Dataset', fontsize=13, fontweight='bold')\n",
        "plt.tight_layout()\n",
        "out = PROCESSED_DIR.parent / 'eda_distribucion.png'\n",
        "plt.savefig(out, dpi=150, bbox_inches='tight')\n",
        "plt.show()\n",
        "plt.close(fig)\n",
        "print(f'Grafico guardado → {out}')\n",
    ], cell_id="plot_dist"),

    code([
        "# ── 4. Muestras visuales por clase (carga lazy) ────────────\n",
        "from PIL import Image\n",
        "import gc\n",
        "\n",
        "fig, axes = plt.subplots(len(CLASSES), EDA_N_VISUAL,\n",
        "                          figsize=(EDA_N_VISUAL * 3, len(CLASSES) * 3))\n",
        "\n",
        "for row, cls in enumerate(CLASSES):\n",
        "    cls_dir = PROCESSED_DIR / 'train' / cls\n",
        "    if not cls_dir.exists():\n",
        "        for col in range(EDA_N_VISUAL):\n",
        "            axes[row][col].axis('off')\n",
        "        continue\n",
        "    imgs = list(cls_dir.glob('*.jpg')) + list(cls_dir.glob('*.png'))\n",
        "    samples = random.sample(imgs, min(EDA_N_VISUAL, len(imgs)))\n",
        "\n",
        "    for col in range(EDA_N_VISUAL):\n",
        "        ax = axes[row][col]\n",
        "        if col < len(samples):\n",
        "            try:\n",
        "                with Image.open(samples[col]) as raw:\n",
        "                    raw.load()\n",
        "                    img = raw.convert('RGB').resize((224, 224), Image.LANCZOS)\n",
        "                ax.imshow(img)\n",
        "            except Exception:\n",
        "                ax.text(0.5, 0.5, 'ERROR', ha='center', va='center',\n",
        "                        transform=ax.transAxes)\n",
        "            ax.set_title(cls if col == 0 else '', fontsize=9, fontweight='bold')\n",
        "        ax.axis('off')\n",
        "\n",
        "plt.suptitle('Muestras por clase (split train)', fontsize=13, fontweight='bold')\n",
        "plt.tight_layout()\n",
        "out = PROCESSED_DIR.parent / 'eda_muestras.png'\n",
        "plt.savefig(out, dpi=120, bbox_inches='tight')\n",
        "plt.show()\n",
        "plt.close(fig)\n",
        "gc.collect()\n",
        "print(f'Muestras guardadas → {out}')\n",
    ], cell_id="samples"),

    code([
        "# ── 5. Analisis de resoluciones (muestreo) ─────────────────\n",
        "import numpy as np\n",
        "from PIL import Image\n",
        "from collections import Counter\n",
        "import time\n",
        "\n",
        "def analyze_resolution(args):\n",
        "    p, cls = args\n",
        "    try:\n",
        "        with Image.open(p) as img:\n",
        "            w, h = img.size\n",
        "            return {'clase': cls, 'w': w, 'h': h, 'ratio': round(w / h, 2)}\n",
        "    except Exception:\n",
        "        return None\n",
        "\n",
        "print(f'Analizando resoluciones (muestra de {EDA_SAMPLE_RES} imgs por clase)...')\n",
        "t0 = time.perf_counter()\n",
        "tasks = []\n",
        "for cls in CLASSES:\n",
        "    cls_dir = PROCESSED_DIR / 'train' / cls\n",
        "    if not cls_dir.exists():\n",
        "        continue\n",
        "    imgs = list(cls_dir.glob('*.jpg'))\n",
        "    if len(imgs) > EDA_SAMPLE_RES:\n",
        "        imgs = random.sample(imgs, EDA_SAMPLE_RES)\n",
        "    for p in imgs:\n",
        "        tasks.append((p, cls))\n",
        "\n",
        "with ThreadPoolExecutor(max_workers=N_WORKERS) as ex:\n",
        "    results = [r for r in ex.map(analyze_resolution, tasks) if r is not None]\n",
        "\n",
        "df_res = pd.DataFrame(results)\n",
        "print(f'  Tiempo: {time.perf_counter()-t0:.2f}s')\n",
        "\n",
        "print('\\nResolucion mas comun (WxH):')\n",
        "res_str = df_res.apply(lambda r: f'{int(r.w)}x{int(r.h)}', axis=1)\n",
        "print(Counter(res_str).most_common(5))\n",
        "\n",
        "print('\\nEstadisticas por clase:')\n",
        "stats = df_res.groupby('clase')[['w', 'h']].agg(['mean', 'min', 'max']).round(0)\n",
"print(stats.to_string())\n",
        "\n",
        "# Scatter de resoluciones\n",
        "fig, ax = plt.subplots(figsize=(8, 5))\n",
        "palette = {'healthy': '#2D6A4F', 'downy_mildew': '#52B788',\n",
        "           'leaf_curl': '#B7E4C7', 'mosaic_virus': '#F4A261',\n",
        "           'red_beetle': '#E76F51'}\n",
        "for cls in CLASSES:\n",
        "    sub = df_res[df_res.clase == cls]\n",
        "    ax.scatter(sub.w, sub.h, label=cls, alpha=0.5, s=20, color=palette[cls])\n",
        "ax.set_xlabel('Ancho (px)')\n",
        "ax.set_ylabel('Alto (px)')\n",
        "ax.set_title('Resoluciones del dataset')\n",
        "ax.legend(markerscale=2)\n",
        "plt.tight_layout()\n",
        "out = PROCESSED_DIR.parent / 'eda_resoluciones.png'\n",
        "plt.savefig(out, dpi=120)\n",
        "plt.show()\n",
        "plt.close(fig)\n",
        "del df_res, results\n",
        "gc.collect()\n",
    ], cell_id="resolutions"),

    code([
        "# ── 6. Analisis de calidad (nitidez, brillo, contraste) ────\n",
        "import cv2\n",
        "\n",
        "def quality_metrics(args):\n",
        "    \"\"\"Calcula nitidez (Laplaciano), brillo y contraste.\"\"\"\n",
        "    p, cls = args\n",
        "    try:\n",
        "        img = cv2.imread(str(p), cv2.IMREAD_GRAYSCALE)\n",
        "        if img is None:\n",
        "            return None\n",
        "        h, w = img.shape\n",
        "        if max(h, w) > 400:\n",
        "            scale = 400 / max(h, w)\n",
        "            img = cv2.resize(img, None, fx=scale, fy=scale,\n",
        "                             interpolation=cv2.INTER_AREA)\n",
        "        lap = cv2.Laplacian(img, cv2.CV_64F)\n",
        "        blur = float(lap.var())\n",
        "        bright = float(img.mean())\n",
        "        contrast = float(img.std())\n",
        "        return {'clase': cls, 'nitidez': blur, 'brillo': bright,\n",
        "                'contraste': contrast}\n",
        "    except Exception:\n",
        "        return None\n",
        "\n",
        "print(f'Analizando calidad en {EDA_SAMPLE_QUAL} imgs por clase...')\n",
        "t0 = time.perf_counter()\n",
        "tasks = []\n",
        "for cls in CLASSES:\n",
        "    cls_dir = PROCESSED_DIR / 'train' / cls\n",
        "    if not cls_dir.exists():\n",
        "        continue\n",
        "    imgs = list(cls_dir.glob('*.jpg'))\n",
        "    if len(imgs) > EDA_SAMPLE_QUAL:\n",
        "        imgs = random.sample(imgs, EDA_SAMPLE_QUAL)\n",
        "    for p in imgs:\n",
        "        tasks.append((p, cls))\n",
        "\n",
        "with ThreadPoolExecutor(max_workers=N_WORKERS) as ex:\n",
        "    q_results = [r for r in ex.map(quality_metrics, tasks) if r is not None]\n",
        "print(f'  Tiempo: {time.perf_counter()-t0:.2f}s')\n",
        "\n",
        "df_qual = pd.DataFrame(q_results)\n",
        "print('\\nEstadisticas de calidad:')\n",
        "stats = df_qual.groupby('clase')[['nitidez', 'brillo', 'contraste']].agg(\n",
        "    ['mean', 'min', 'max']).round(2)\n",
        "print(stats.to_string())\n",
        "\n",
        "BLUR_THRESHOLD = 80.0\n",
        "BRIGHT_MIN, BRIGHT_MAX = 35.0, 225.0\n",
        "low_quality = df_qual[\n",
        "    (df_qual['nitidez'] < BLUR_THRESHOLD) |\n",
        "    (df_qual['brillo'] < BRIGHT_MIN) |\n",
        "    (df_qual['brillo'] > BRIGHT_MAX)\n",
        "]\n",
        "pct = 100 * len(low_quality) / len(df_qual) if len(df_qual) > 0 else 0\n",
        "print(f'\\nImagenes con problemas de calidad:')\n",
        "print(f'  {len(low_quality)}/{len(df_qual)} ({pct:.1f}%)')\n",
        "print(f'  (umbral: nitidez<{BLUR_THRESHOLD}, brillo<{BRIGHT_MIN} o >{BRIGHT_MAX})')\n",
        "\n",
        "del df_qual, q_results\n",
        "gc.collect()\n",
    ], cell_id="quality"),

    code([
        "# ── 7. Deteccion de duplicados (muestreo) ──────────────────\n",
        "import imagehash\n",
        "\n",
        "def hash_one(args):\n",
        "    p, cls = args\n",
        "    try:\n",
        "        with Image.open(p) as img:\n",
        "            h = str(imagehash.phash(img, hash_size=8))\n",
        "        return (h, cls, str(p))\n",
        "    except Exception:\n",
        "        return None\n",
        "\n",
        "print('Detectando duplicados (pHash, muestra 500/clase)...')\n",
        "t0 = time.perf_counter()\n",
        "tasks = []\n",
        "for cls in CLASSES:\n",
        "    cls_dir = PROCESSED_DIR / 'train' / cls\n",
        "    if not cls_dir.exists():\n",
        "        continue\n",
        "    imgs = list(cls_dir.glob('*.jpg'))\n",
        "    if len(imgs) > 500:\n",
        "        imgs = random.sample(imgs, 500)\n",
        "    for p in imgs:\n",
        "        tasks.append((p, cls))\n",
        "\n",
        "hashes_by_cls = {c: {} for c in CLASSES}\n",
        "with ThreadPoolExecutor(max_workers=N_WORKERS) as ex:\n",
        "    for r in ex.map(hash_one, tasks):\n",
        "        if r is None:\n",
        "            continue\n",
        "        h, cls, path = r\n",
        "        hashes_by_cls[cls].setdefault(h, []).append(path)\n",
        "print(f'  Tiempo: {time.perf_counter()-t0:.2f}s')\n",
        "\n",
        "print('\\nDuplicados aproximados por clase:')\n",
        "for cls, hash_map in hashes_by_cls.items():\n",
        "    dup_groups = [v for v in hash_map.values() if len(v) > 1]\n",
        "    n_dup = sum(len(g) - 1 for g in dup_groups)\n",
        "    total = sum(len(v) for v in hash_map.values())\n",
"    print(f'  {cls:<20}: {n_dup} duplicados en {total}')\n",
        "del hashes_by_cls\n",
        "gc.collect()\n",
    ], cell_id="duplicates"),

    code([
        "# ── 8. Resumen estadistico final ───────────────────────────\n",
        "total = pivot.loc['TOTAL', 'TOTAL']\n",
        "total_train = pivot.loc['TOTAL', 'train']\n",
        "total_val   = pivot.loc['TOTAL', 'val']\n",
        "total_test  = pivot.loc['TOTAL', 'test']\n",
        "\n",
        "print('=== RESUMEN DATASET ZapalloAI ===')\n",
        "print(f'Total imagenes  : {int(total):,}')\n",
        "print(f'  Train (70%)   : {int(total_train):,}')\n",
        "print(f'  Val   (15%)   : {int(total_val):,}')\n",
        "print(f'  Test  (15%)   : {int(total_test):,}')\n",
        "print(f'Num clases      : {len(CLASSES)}')\n",
        "print()\n",
        "\n",
        "train_per_cls = [pivot.loc[c, 'train'] for c in CLASSES]\n",
        "ratio = max(train_per_cls) / min(train_per_cls)\n",
        "mayor = CLASSES[train_per_cls.index(max(train_per_cls))]\n",
        "menor = CLASSES[train_per_cls.index(min(train_per_cls))]\n",
        "print(f'Clase mayor     : {mayor} ({int(max(train_per_cls)):,} imgs)')\n",
        "print(f'Clase menor     : {menor} ({int(min(train_per_cls)):,} imgs)')\n",
        "print(f'Ratio max/min   : {ratio:.2f}x',\n",
        "      '(balanceado)' if ratio <= 3 else '(necesita augmentation)')\n",
        "print()\n",
        "print('Dataset listo para entrenamiento')\n",
        "print('Siguiente: python model/scripts/train.py')\n",
    ], cell_id="summary"),

])


# ─── Notebook 02: Evaluacion ────────────────────────────────────────

NOTEBOOK_02_CELLS = _cells([

    md([
        "# ZapalloAI — Notebook 02: Evaluacion del Modelo\n",
        "\n",
        "**Universidad de las Fuerzas Armadas ESPE**  \n",
        "**Estudiantes:** César Loor, Camilo Orrico  \n",
        "**Docente:** Ing. Doris Chicaiza\n",
        "\n",
        "Evaluación del modelo entrenado (`best.pt`) sobre el **test set**.",
        "Genera matriz de confusión, métricas por clase y ejemplos visuales.\n",
        "\n",
        "---\n",
        "\n",
        "## Prerrequisito\n",
        "\n",
        "Ejecutar primero:\n",
        "```bash\n",
        "python model/scripts/train.py\n",
        "```\n",
    ]),

    code([
        "# ── 0. Dependencias ─────────────────────────────────────────\n",
        "try:\n",
        "    import torch, ultralytics, matplotlib, sklearn, seaborn, pandas\n",
        "    print('OK - Dependencias ya instaladas')\n",
        "except ImportError:\n",
        "    import subprocess, sys\n",
        "    subprocess.run([sys.executable, '-m', 'pip', 'install', '-q',\n",
        "                    'ultralytics', 'matplotlib', 'scikit-learn',\n",
        "                    'seaborn', 'pandas'], check=False)\n",
        "    print('OK - Dependencias instaladas')\n",
    ], cell_id="deps"),

    code([
        "# ── 1a. Cargar metricas desde JSON (si existen) ────────────\n",
        "from pathlib import Path\n",
        "import sys\n",
        "sys.path.insert(0, str(Path.cwd() / 'model'))\n",
        "from config import CLASSES, EXPORT_DIR, PROCESSED_DIR, RUNS_DIR\n",
        "\n",
        "metrics_path = EXPORT_DIR / 'training_metrics.json'\n",
        "val_path = EXPORT_DIR / 'validation_results.json'\n",
        "\n",
        "if metrics_path.exists() and val_path.exists():\n",
        "    import json\n",
        "    tm = json.loads(metrics_path.read_text(encoding='utf-8'))\n",
        "    vm = json.loads(val_path.read_text(encoding='utf-8'))\n",
        "    print('=== Metricas desde archivos JSON ===')\n",
        "    print(f'Run: {tm[\"run_name\"]}')\n",
        "    print(f'Mejor epoch: {tm[\"best_epoch_metrics\"].get(\"epoch\", \"?\")}')\n",
        "    print(f'Top-1 (val): {tm[\"best_epoch_metrics\"].get(\"top1\", \"?\")}')\n",
        "    print(f'Top-1 (test): {vm.get(\"top1\", \"?\")}')\n",
        "    print(f'Top-5 (test): {vm.get(\"top5\", \"?\")}')\n",
        "    print('(Celdas siguientes cargan el modelo para analisis detallado)')\n",
        "else:\n",
        "    print('training_metrics.json o validation_results.json no encontrados.')\n",
        "    print('Ejecuta primero: python model/scripts/train.py')\n",
        "    print('Celdas siguientes ejecutaran validacion manual.')\n",
    ], cell_id="load_json"),

    code([
        "# ── 1b. Importar config y localizar mejor modelo ────────────\n",
        "from pathlib import Path\n",
        "\n",
        "sys.path.insert(0, str(Path.cwd() / 'model'))\n",
        "from config import CLASSES, RUNS_DIR, EXPORT_DIR, PROCESSED_DIR\n",
        "\n",
        "# Buscar el mejor checkpoint\n",
        "candidates = sorted(RUNS_DIR.rglob('weights/best.pt'))\n",
        "if not candidates:\n",
        "    raise FileNotFoundError(\n",
        "        f'No se encontro best.pt en {RUNS_DIR}\\n'\n",
        "        'Ejecuta primero: python model/scripts/train.py'\n",
        "    )\n",
        "best_pt = candidates[-1]\n",
        "run_dir = best_pt.parents[2]\n",
        "print(f'Mejor modelo: {best_pt}')\n",
        "print(f'Run dir     : {run_dir}')\n",
        "print(f'Test set    : {PROCESSED_DIR / \"test\"}')\n",
    ], cell_id="locate_model"),

    code([
        "# ── 2. Validacion en test set ───────────────────────────────\n",
        "from ultralytics import YOLO\n",
        "import torch\n",
        "import time\n",
        "\n",
        "assert torch.cuda.is_available(), 'GPU no disponible'\n",
        "\n",
        "vram_gb = torch.cuda.get_device_properties(0).total_memory / 1024**3\n",
        "batch = 4 if vram_gb < 6 else 16\n",
        "\n",
        "model = YOLO(str(best_pt))\n",
        "\n",
        "print('Evaluando en test set...')\n",
        "t0 = time.perf_counter()\n",
        "metrics = model.val(\n",
        "    data=str(PROCESSED_DIR),\n",
        "    split='test',\n",
        "    imgsz=224,\n",
        "    batch=batch,\n",
        "    device=0,\n",
        "    workers=0,\n",
        "    verbose=True,\n",
        "    plots=True,\n",
        "    save_json=True,\n",
        ")\n",
        "elapsed = time.perf_counter() - t0\n",
        "print(f'\\nTiempo de validacion: {elapsed:.1f}s')\n",
        "print(f'Top-1 Accuracy: {metrics.top1:.4f}')\n",
        "print(f'Top-5 Accuracy: {metrics.top5:.4f}')\n",
    ], cell_id="validation"),

    code([
        "# ── 3. Matriz de confusion ─────────────────────────────────\n",
        "import matplotlib.pyplot as plt\n",
        "import matplotlib\n",
        "matplotlib.rcParams.update({'font.family': 'DejaVu Sans'})\n",
        "\n",
        "# Buscar matriz generada por YOLO\n",
        "cm_sources = list(run_dir.glob('confusion_matrix*.png'))\n",
        "if cm_sources:\n",
        "    cm_path = cm_sources[-1]\n",
        "    img = plt.imread(str(cm_path))\n",
        "    fig, ax = plt.subplots(figsize=(8, 7))\n",
        "    ax.imshow(img)\n",
        "    ax.axis('off')\n",
        "    ax.set_title('Matriz de Confusion (test set)', fontsize=12, fontweight='bold')\n",
        "    plt.tight_layout()\n",
        "    plt.show()\n",
        "    plt.close(fig)\n",
        "    \n",
        "    # Copiar a exports/\n",
        "    import shutil\n",
        "    EXPORT_DIR.mkdir(parents=True, exist_ok=True)\n",
        "    dst = EXPORT_DIR / 'confusion_matrix.png'\n",
        "    shutil.copy2(str(cm_path), str(dst))\n",
        "    print(f'Matriz copiada a: {dst}')\n",
        "else:\n",
        "    print('No se encontro matriz generada por YOLO')\n",
        "    print('Regenerando manualmente...')\n",
        "    from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay\n",
        "    import numpy as np\n",
        "    \n",
        "    y_true, y_pred = [], []\n",
        "    from pathlib import Path\n",
        "    for cls_dir in sorted((PROCESSED_DIR / 'test').iterdir()):\n",
        "        if not cls_dir.is_dir():\n",
        "            continue\n",
        "        cls_name = cls_dir.name\n",
        "        cls_idx = CLASSES.index(cls_name)\n",
        "        for img_path in list(cls_dir.glob('*.jpg'))[:50]:\n",
        "            results = model(str(img_path))\n",
        "            has_probs = hasattr(results[0], 'probs')\n",
"            pred_idx = int(results[0].probs.top1) if has_probs else 0\n",
        "            y_true.append(cls_idx)\n",
        "            y_pred.append(pred_idx)\n",
        "    \n",
        "    cm = confusion_matrix(y_true, y_pred, labels=range(len(CLASSES)))\n",
        "    disp = ConfusionMatrixDisplay(\n",
        "        confusion_matrix=cm, display_labels=CLASSES)\n",
        "    fig, ax = plt.subplots(figsize=(8, 7))\n",
        "    disp.plot(ax=ax, cmap='Blues', xticks_rotation=20, values_format='d')\n",
        "    ax.set_title('Matriz de Confusion (test set - manual)')\n",
        "    plt.tight_layout()\n",
        "    plt.show()\n",
        "    plt.close(fig)\n",
    ], cell_id="confusion_matrix"),

    code([
        "# ── 4. Metricas detalladas por clase ────────────────────────\n",
        "import pandas as pd\n",
        "\n",
        "# Extraer metricas del archivo results.csv\n",
        "csv_path = run_dir / 'results.csv'\n",
        "if csv_path.exists():\n",
        "    df = pd.read_csv(csv_path)\n",
        "    df.columns = df.columns.str.strip()\n",
        "    print('=== Curvas de entrenamiento ===')\n",
        "    if 'metrics/accuracy_top1' in df.columns:\n",
        "        best_acc = df['metrics/accuracy_top1'].max()\n",
        "        best_epoch = df['metrics/accuracy_top1'].idxmax() + 1\n",
        "        print(f'Mejor Top-1 Val Accuracy: {best_acc:.4f} (epoch {best_epoch})')\n",
        "    if 'train/loss' in df.columns and 'val/loss' in df.columns:\n",
        "        fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n",
        "        axes[0].plot(df['epoch'], df['train/loss'], label='Train', color='#2D6A4F')\n",
        "        axes[0].plot(df['epoch'], df['val/loss'], label='Val', color='#E76F51')\n",
        "        axes[0].set_xlabel('Epoch')\n",
        "        axes[0].set_ylabel('Loss')\n",
        "        axes[0].set_title('Loss')\n",
        "        axes[0].legend()\n",
        "        \n",
        "        if 'metrics/accuracy_top1' in df.columns:\n",
        "            axes[1].plot(df['epoch'], df['metrics/accuracy_top1'],\n",
        "                        label='Top-1', color='#2D6A4F')\n",
        "            axes[1].set_xlabel('Epoch')\n",
        "            axes[1].set_ylabel('Accuracy')\n",
        "            axes[1].set_title('Top-1 Accuracy')\n",
        "            axes[1].legend()\n",
        "        \n",
        "        plt.suptitle('Curvas de Entrenamiento', fontweight='bold')\n",
        "        plt.tight_layout()\n",
        "        plt.show()\n",
        "        plt.close(fig)\n",
        "else:\n",
        "    print('results.csv no encontrado en', run_dir)\n",
        "\n",
        "# Metrica por clase desde YOLO\n",
        "print('\\n=== Metricas por clase (test set) ===')\n",
        "print(f'{\"Clase\":<20} {\"support\":>8} {\"top1_acc\":>10}')\n",
        "print('-' * 40)\n",
        "# YOLO no da metricas por clase directamente en clasificacion\n",
        "# Simular con predicciones en test\n",
        "print('(ejecutando inferencia en test para metricas por clase...)')\n",
        "from collections import defaultdict\n",
        "correct = defaultdict(int)\n",
        "total = defaultdict(int)\n",
        "for cls in CLASSES:\n",
        "    cls_dir = PROCESSED_DIR / 'test' / cls\n",
        "    if not cls_dir.exists():\n",
        "        continue\n",
        "    imgs = list(cls_dir.glob('*.jpg'))[:100]\n",
        "    for img_path in imgs:\n",
        "        results = model(str(img_path))\n",
        "        pred = results[0].probs.top1\n",
        "        total[cls] += 1\n",
        "        if CLASSES[pred] == cls:\n",
        "            correct[cls] += 1\n",
        "\n",
        "for cls in CLASSES:\n",
        "    t = total[cls]\n",
        "    c = correct[cls]\n",
        "    acc = c / t if t > 0 else 0\n",
        "    print(f'{cls:<20} {t:>8} {acc:>10.4f}')\n",
    ], cell_id="per_class_metrics"),

    code([
        "# ── 5. Ejemplos de clasificacion correcta e incorrecta ──────\n",
        "import random\n",
        "from PIL import Image\n",
        "\n",
        "correct_examples = {cls: [] for cls in CLASSES}\n",
        "incorrect_examples = {cls: [] for cls in CLASSES}\n",
        "\n",
        "print('Recolectando ejemplos...')\n",
        "for cls in CLASSES:\n",
        "    cls_dir = PROCESSED_DIR / 'test' / cls\n",
        "    if not cls_dir.exists():\n",
        "        continue\n",
        "    imgs = list(cls_dir.glob('*.jpg'))[:200]\n",
        "    for img_path in imgs:\n",
        "        results = model(str(img_path))\n",
        "        pred = CLASSES[results[0].probs.top1]\n",
        "        conf = float(results[0].probs.top1conf)\n",
        "        example = (img_path, conf)\n",
        "        if pred == cls:\n",
        "            correct_examples[cls].append(example)\n",
        "        else:\n",
        "            incorrect_examples[cls].append((img_path, pred, conf))\n",
        "\n",
        "fig, axes = plt.subplots(3, 4, figsize=(14, 10))\n",
        "# Fila 0-1: Correctos\n",
        "for i, cls in enumerate(CLASSES):\n",
        "    if i >= 4:\n",
        "        break\n",
        "    examples = correct_examples[cls][:2]\n",
        "    for j, (path, conf) in enumerate(examples):\n",
        "        if j >= 2:\n",
        "            continue\n",
        "        ax = axes[j][i]\n",
        "        with Image.open(path) as raw:\n",
        "            img = raw.convert('RGB').resize((112, 112))\n",
        "        ax.imshow(img)\n",
        "        ax.set_title(f'Correcto: {cls}\\nconf={conf:.3f}', fontsize=8)\n",
        "        ax.axis('off')\n",
        "\n",
        "# Fila 2: Incorrectos\n",
        "all_incorrect = []\n",
        "for cls, examples in incorrect_examples.items():\n",
        "    all_incorrect.extend(examples)\n",
        "random.shuffle(all_incorrect)\n",
        "for j in range(min(4, len(all_incorrect))):\n",
        "    ax = axes[2][j]\n",
        "    path, pred, conf = all_incorrect[j]\n",
        "    true_cls = path.parent.name\n",
        "    with Image.open(path) as raw:\n",
        "        img = raw.convert('RGB').resize((112, 112))\n",
        "    ax.imshow(img)\n",
        "    title = f'Real: {true_cls}\\nPred: {pred} ({conf:.3f})'\n",
"    ax.set_title(title, fontsize=8, color='red')\n",
        "    ax.axis('off')\n",
        "\n",
        "for i in range(4):\n",
        "    for j in range(3):\n",
        "        if axes[j][i].get_title() == '':\n",
        "            axes[j][i].axis('off')\n",
        "\n",
        "plt.suptitle('Ejemplos de clasificacion (correctos e incorrectos)',\n",
        "             fontsize=12, fontweight='bold')\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "plt.close(fig)\n",
    ], cell_id="examples"),

    code([
        "# ── 6. Comparacion PyTorch vs TFLite ────────────────────────\n",
        "from ultralytics import YOLO\n",
        "import numpy as np\n",
        "import time\n",
        "\n",
        "tflite_path = EXPORT_DIR / 'best_int8.tflite'\n",
        "if not tflite_path.exists():\n",
        "    print('TFLite no encontrado. Ejecuta train.py o exporta manualmente.')\n",
        "    print('Saltando comparacion.')\n",
        "else:\n",
        "    print('Comparando precision PyTorch vs TFLite...')\n",
        "    model_pt = YOLO(str(best_pt))\n",
        "    model_tflite = YOLO(str(tflite_path))\n",
        "    \n",
        "    pytorch_correct = 0\n",
        "    tflite_correct = 0\n",
        "    total_test = 0\n",
        "    \n",
        "    for cls in CLASSES:\n",
        "        cls_dir = PROCESSED_DIR / 'test' / cls\n",
        "        if not cls_dir.exists():\n",
        "            continue\n",
        "        cls_idx = CLASSES.index(cls)\n",
        "        imgs = list(cls_dir.glob('*.jpg'))[:30]\n",
        "        for img_path in imgs:\n",
        "            r_pt = model_pt(str(img_path))\n",
        "            r_tf = model_tflite(str(img_path))\n",
        "            if CLASSES[r_pt[0].probs.top1] == cls:\n",
        "                pytorch_correct += 1\n",
        "            if CLASSES[r_tf[0].probs.top1] == cls:\n",
        "                tflite_correct += 1\n",
        "            total_test += 1\n",
        "    \n",
        "    print(f'\\nPyTorch accuracy: {pytorch_correct}/{total_test}'\n",
        "          f' ({100*pytorch_correct/total_test:.1f}%)')\n",
        "    print(f'TFLite  accuracy: {tflite_correct}/{total_test}'\n",
        "          f' ({100*tflite_correct/total_test:.1f}%)')\n",
        "    diff = abs(pytorch_correct - tflite_correct)\n",
        "    if diff <= 2:\n",
        "        print('\\nDiferencia minima. Cuantizacion ok.')\n",
        "    else:\n",
        "        print(f'\\nDiferencia de {diff} muestras. Revisar calibracion.')\n",
    ], cell_id="pt_vs_tflite"),

    code([
        "# ── 7. Resumen final ────────────────────────────────────────\n",
        "print('=== RESUMEN EVALUACION ZapalloAI ===')\n",
        "print(f'Modelo         : {best_pt}')\n",
        "print(f'Top-1 Accuracy : {metrics.top1:.4f}')\n",
        "print(f'Top-5 Accuracy : {metrics.top5:.4f}')\n",
        "print(f'Test set       : {PROCESSED_DIR / \"test\"}')\n",
        "print()\n",
        "print('Archivos generados:')\n",
        "print(f'  - Matriz confusion: {EXPORT_DIR / \"confusion_matrix.png\"}')\n",
        "print()\n",
        "print('Si las metricas son aceptables, desplegar en Flutter:')\n",
        "print('  los archivos ya estan en:')\n",
        "print(f'    {EXPORT_DIR / \"best_int8.tflite\"}')\n",
        "print(f'    {EXPORT_DIR / \"labels.txt\"}')\n",
        "print('  y se copiaron automaticamente a zapallo_app/assets/models/')\n",
    ], cell_id="summary"),

])


# ─── Notebook 03: Despliegue ────────────────────────────────────────

NOTEBOOK_03_CELLS = _cells([

    md([
        "# ZapalloAI — Notebook 03: Despliegue e Inferencia\n",
        "\n",
        "**Universidad de las Fuerzas Armadas ESPE**  \n",
        "**Estudiantes:** César Loor, Camilo Orrico  \n",
        "**Docente:** Ing. Doris Chicaiza\n",
        "\n",
        "Prueba del modelo exportado a TFLite sobre imágenes reales.",
        "Verifica que el modelo cuantizado funcione correctamente y mide latencia.\n",
        "\n",
        "---\n",
        "\n",
        "## Prerrequisito\n",
        "\n",
        "Ejecutar primero:\n",
        "```bash\n",
        "python model/scripts/train.py\n",
        "```\n",
    ]),

    code([
        "# ── 0. Dependencias ─────────────────────────────────────────\n",
        "try:\n",
        "    import tensorflow, PIL, matplotlib, numpy\n",
        "    print('OK - Dependencias ya instaladas')\n",
        "except ImportError:\n",
        "    import subprocess, sys\n",
        "    subprocess.run([sys.executable, '-m', 'pip', 'install', '-q',\n",
        "                    'tensorflow', 'Pillow', 'matplotlib', 'numpy'],\n",
        "                   check=False)\n",
        "    print('OK - Dependencias instaladas')\n",
    ], cell_id="deps"),

    code([
        "# ── 1a. Cargar info del modelo desde training_metrics.json ─\n",
        "from pathlib import Path\n",
        "import sys\n",
        "sys.path.insert(0, str(Path.cwd() / 'model'))\n",
        "from config import EXPORT_DIR\n",
        "\n",
        "metrics_path = EXPORT_DIR / 'training_metrics.json'\n",
        "if metrics_path.exists():\n",
        "    import json\n",
        "    tm = json.loads(metrics_path.read_text(encoding='utf-8'))\n",
        "    print('=== Info del modelo (desde training_metrics.json) ===')\n",
        "    print(f'Run: {tm[\"run_name\"]}')\n",
        "    print(f'Config: epochs={tm[\"config\"][\"epochs\"]}, '\n",
        "          f'batch={tm[\"config\"][\"batch\"]}, '\n",
        "          f'AMP={tm[\"config\"][\"amp\"]}')\n",
        "    print(f'Test Top-1: {tm[\"test_set_metrics\"].get(\"top1\", \"?\")}')\n",
        "    print(f'Test Top-5: {tm[\"test_set_metrics\"].get(\"top5\", \"?\")}')\n",
        "    print('(Celdas siguientes cargan TFLite para inferencia)')\n",
        "else:\n",
        "    print('training_metrics.json no encontrado.')\n",
        "    print('Ejecuta primero: python model/scripts/train.py')\n",
        "    print('Celdas siguientes cargaran TFLite manualmente.')\n",
    ], cell_id="load_json"),

    code([
        "# ── 1b. Importar config y cargar TFLite ────────────────────\n",
        "from pathlib import Path\n",
        "import sys\n",
        "\n",
        "sys.path.insert(0, str(Path.cwd() / 'model'))\n",
        "from config import CLASSES, EXPORT_DIR, PROCESSED_DIR, FLUTTER_TFLITE, FLUTTER_LABELS\n",
        "\n",
        "# Cargar labels\n",
        "labels_path = EXPORT_DIR / 'labels.txt'\n",
        "if labels_path.exists():\n",
        "    labels = labels_path.read_text().strip().splitlines()\n",
        "    print(f'Labels ({len(labels)}): {labels}')\n",
        "else:\n",
        "    labels = CLASSES\n",
        "    print(f'Usando CLASSES de config: {labels}')\n",
    ], cell_id="config"),

    code([
        "# ── 2. Cargar interpreter de TFLite ─────────────────────────\n",
        "import tensorflow as tf\n",
        "import numpy as np\n",
        "\n",
        "tflite_path = EXPORT_DIR / 'best_int8.tflite'\n",
        "if not tflite_path.exists():\n",
        "    # Buscar en Flutter assets\n",
        "    if FLUTTER_TFLITE.exists():\n",
        "        tflite_path = FLUTTER_TFLITE\n",
        "    else:\n",
        "        raise FileNotFoundError(\n",
        "            f'TFLite no encontrado en {tflite_path} ni {FLUTTER_TFLITE}\\n'\n",
        "            'Ejecuta: python model/scripts/train.py'\n",
        "        )\n",
        "\n",
        "interpreter = tf.lite.Interpreter(model_path=str(tflite_path))\n",
        "interpreter.allocate_tensors()\n",
        "\n",
        "input_details = interpreter.get_input_details()\n",
        "output_details = interpreter.get_output_details()\n",
        "\n",
        "input_shape = input_details[0]['shape']\n",
        "input_dtype = input_details[0]['dtype']\n",
        "output_shape = output_details[0]['shape']\n",
        "\n",
        "print(f'Modelo TFLite: {tflite_path.name}')\n",
        "print(f'  Input shape : {input_shape}')\n",
        "print(f'  Input dtype : {input_dtype}')\n",
        "print(f'  Output shape: {output_shape}')\n",
        "print(f'  Output dtype: {output_details[0][\"dtype\"]}')\n",
        "print(f'  Tamaño      : {tflite_path.stat().st_size / 1024**2:.2f} MB')\n",
    ], cell_id="load_tflite"),

    code([
        "# ── 3. Funcion de preprocesamiento (igual que en Flutter) ───\n",
        "from PIL import Image\n",
        "\n",
        "def preprocess_image(path, target_size=(224, 224)):\n",
        "    \"\"\"Preprocesa imagen como lo hara la app Flutter.\"\"\"\n",
        "    with Image.open(path) as raw:\n",
        "        if raw.mode != 'RGB':\n",
        "            raw = raw.convert('RGB')\n",
        "        # Redimensionar manteniendo aspect ratio + pad\n",
        "        raw.thumbnail(target_size, Image.LANCZOS)\n",
        "        img = Image.new('RGB', target_size, (0, 0, 0))\n",
        "        offset = (\n",
        "            (target_size[0] - raw.size[0]) // 2,\n",
        "            (target_size[1] - raw.size[1]) // 2,\n",
        "        )\n",
        "        img.paste(raw, offset)\n",
        "        # Normalizar a [0, 1] y convertir a uint8\n",
        "        arr = np.array(img, dtype=np.float32) / 255.0\n",
        "        if input_dtype == np.uint8:\n",
        "            arr = (arr * 255).astype(np.uint8)\n",
        "        # Batch dimension\n",
        "        arr = np.expand_dims(arr, axis=0)\n",
        "        return arr\n",
        "\n",
        "def predict(path):\n",
        "    \"\"\"Ejecuta inferencia en una imagen.\"\"\"\n",
        "    input_data = preprocess_image(path)\n",
        "    interpreter.set_tensor(input_details[0]['index'], input_data)\n",
        "    interpreter.invoke()\n",
        "    output = interpreter.get_tensor(output_details[0]['index'])\n",
        "    probs = output[0]\n",
        "    # Softmax si el output no esta normalizado\n",
        "    if probs.sum() > 1.1 or probs.sum() < 0.9:\n",
        "        probs = np.exp(probs) / np.exp(probs).sum()\n",
        "    pred_idx = int(np.argmax(probs))\n",
        "    confidence = float(probs[pred_idx])\n",
        "    return labels[pred_idx], confidence, probs\n",
        "\n",
        "print('Funcion predict() lista')\n",
    ], cell_id="preprocess"),

    code([
        "# ── 4. Ejemplos de inferencia en test set ───────────────────\n",
        "import matplotlib.pyplot as plt\n",
        "import random\n",
        "\n",
        "print('Probando el modelo TFLite en imagenes de test...')\n",
        "\n",
        "fig, axes = plt.subplots(2, 4, figsize=(16, 8))\n",
        "examples = []\n",
        "for cls in CLASSES:\n",
        "    cls_dir = PROCESSED_DIR / 'test' / cls\n",
        "    if not cls_dir.exists():\n",
        "        continue\n",
        "    imgs = list(cls_dir.glob('*.jpg'))[:3]\n",
        "    for p in imgs:\n",
        "        examples.append((p, cls))\n",
        "\n",
        "random.shuffle(examples)\n",
        "\n",
        "for i, (img_path, true_cls) in enumerate(examples[:8]):\n",
        "    ax = axes[i // 4][i % 4]\n",
        "    \n",
        "    pred_cls, confidence, probs = predict(img_path)\n",
        "    \n",
        "    with Image.open(img_path) as raw:\n",
        "        img = raw.convert('RGB').resize((128, 128))\n",
        "    ax.imshow(img)\n",
        "    \n",
        "    color = 'green' if pred_cls == true_cls else 'red'\n",
        "    title = f'Real: {true_cls}\\nPred: {pred_cls} ({confidence:.3f})'\n",
        "    ax.set_title(title, fontsize=9, color=color)\n",
        "    ax.axis('off')\n",
        "\n",
        "plt.suptitle('Inferencia TFLite en imagenes de test',\n",
        "             fontsize=13, fontweight='bold')\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "plt.close(fig)\n",
    ], cell_id="inference_examples"),

    code([
        "# ── 5. Metricas de latencia ─────────────────────────────────\n",
        "import time\n",
        "\n",
        "# Recolectar paths de test\n",
        "test_imgs = []\n",
        "for cls in CLASSES:\n",
        "    cls_dir = PROCESSED_DIR / 'test' / cls\n",
        "    if cls_dir.exists():\n",
        "        test_imgs.extend(list(cls_dir.glob('*.jpg'))[:50])\n",
        "\n",
        "print(f'Midiento latencia en {len(test_imgs)} imagenes...')\n",
        "\n",
        "# Warmup\n",
        "for _ in range(5):\n",
        "    predict(random.choice(test_imgs))\n",
        "\n",
        "# Benchmark\n",
        "times = []\n",
        "for img_path in test_imgs:\n",
        "    t0 = time.perf_counter()\n",
        "    predict(img_path)\n",
        "    times.append(time.perf_counter() - t0)\n",
        "\n",
        "times_ms = np.array(times) * 1000\n",
        "print(f'\\nBenchmark TFLite ({len(times)} muestras):')\n",
        "print(f'  Media    : {times_ms.mean():.1f} ms')\n",
        "print(f'  Mediana  : {np.median(times_ms):.1f} ms')\n",
        "print(f'  Std      : {times_ms.std():.1f} ms')\n",
        "print(f'  Min      : {times_ms.min():.1f} ms')\n",
        "print(f'  Max      : {times_ms.max():.1f} ms')\n",
        "print(f'  P99      : {np.percentile(times_ms, 99):.1f} ms')\n",
        "\n",
        "# Histograma\n",
        "fig, ax = plt.subplots(figsize=(8, 4))\n",
        "ax.hist(times_ms, bins=30, color='#2D6A4F', edgecolor='white')\n",
        "ax.axvline(times_ms.mean(), color='red', linestyle='--',\n",
        "           label=f'Media: {times_ms.mean():.1f}ms')\n",
        "ax.set_xlabel('Tiempo de inferencia (ms)')\n",
        "ax.set_ylabel('Frecuencia')\n",
        "ax.set_title('Distribucion de latencia TFLite')\n",
        "ax.legend()\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "plt.close(fig)\n",
    ], cell_id="latency"),

    code([
        "# ── 6. Verificar consistencia labels.txt ────────────────────\n",
        "print('=== Verificacion de labels.txt ===')\n",
        "\n",
        "labels_desde_archivo = labels  # cargado al inicio\n",
        "print(f'labels.txt        : {labels_desde_archivo}')\n",
        "print(f'config.CLASSES    : {CLASSES}')\n",
        "\n",
        "if labels_desde_archivo == CLASSES:\n",
        "    print('\\nConsistentes. El orden coincide con YOLO.')\n",
        "else:\n",
        "    print('\\nINCONSISTENCIA. Revisar train.py (labels.txt).')\n",
        "    print(f'  Diferencia: {set(labels_desde_archivo) ^ set(CLASSES)}')\n",
        "\n",
        "# Verificar output del modelo\n",
        "print(f'\\nOutput del modelo TFLite:')\n",
        "print(f'  {len(labels)} clases: {labels}')\n",
        "print(f'  Indices del output corresponden a este orden.')\n",
        "print()\n",
        "print('En Flutter, la app lee labels.txt y mapea el indice del modelo')\n",
        "print('a la etiqueta de texto. Coherente con YOLOv11n-cls.')\n",
    ], cell_id="verify_labels"),

    code([
        "# ── 7. Resumen final ────────────────────────────────────────\n",
        "print('=== RESUMEN DESPLIEGUE ZapalloAI ===')\n",
        "print(f'Modelo TFLite : {tflite_path.name}')\n",
        "print(f'  Tamaño      : {tflite_path.stat().st_size / 1024**2:.2f} MB')\n",
        "print(f'  Input       : {input_shape}')\n",
        "print(f'  Output      : {len(labels)} clases')\n",
        "print(f'  Latencia    : {times_ms.mean():.1f} ms (media)')\n",
        "print()\n",
        "print('Archivos para Flutter:')\n",
        "print(f'  - {FLUTTER_TFLITE}')\n",
        "print(f'  - {FLUTTER_LABELS}')\n",
        "print()\n",
        "print('Flujo completo:')\n",
        "print('  1. python model/scripts/preprocess.py    # preparar datos')\n",
        "print('  2. python model/scripts/train.py         # entrenar + exportar')\n",
        "print('  3. Abrir notebooks para EDA, eval, test')\n",
        "print('  4. flutter build apk --release            # compilar app')\n",
    ], cell_id="summary"),

])


# ─── MAIN ───────────────────────────────────────────────────────────

def write_notebook(path, data):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=1, ensure_ascii=False)
    print(f"  Escrito: {path} ({len(data['cells'])} celdas)")


def main():
    print("=== Actualizando notebooks ZapalloAI ===\n")

    # --- Notebook 01 ---
    n01 = NOTEBOOKS_DIR / "01_exploracion_datos.ipynb"
    write_notebook(n01, notebook(NOTEBOOK_01_CELLS))

    # --- Notebook 02 (reemplaza 02_preprocesamiento.ipynb) ---
    old_02 = NOTEBOOKS_DIR / "02_preprocesamiento.ipynb"
    if old_02.exists():
        old_02.unlink()
        print(f"  Eliminado: {old_02}")
    n02 = NOTEBOOKS_DIR / "02_evaluacion.ipynb"
    write_notebook(n02, notebook(NOTEBOOK_02_CELLS))

    # --- Notebook 03 (reemplaza 03_entrenamiento_yolov11.ipynb) ---
    old_03 = NOTEBOOKS_DIR / "03_entrenamiento_yolov11.ipynb"
    if old_03.exists():
        old_03.unlink()
        print(f"  Eliminado: {old_03}")
    n03 = NOTEBOOKS_DIR / "03_despliegue.ipynb"
    write_notebook(n03, notebook(NOTEBOOK_03_CELLS))

    print("\n✅ Notebooks actualizados.")


if __name__ == "__main__":
    main()
